In [1]:
import numpy as np
import chainer
from chainer import Function, gradient_check, report, training, utils, Variable
from chainer import datasets, iterators, optimizers, serializers
from chainer import link, Chain, ChainList
import chainer.function as F
import chainer.link as L
from chainer.training import extensions

/Users/yohei/.pyenv/versions/3.6.4/envs/chainer/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/Users/yohei/.pyenv/versions/3.6.4/envs/chainer/lib/python3.6/site-packages/chainer/_environment_check.py:38: UserWarning: Accelerate has been detected as a NumPy backend library.
vecLib, which is a part of Accelerate, is known not to work correctly with Chainer.
We recommend using other BLAS libraries such as OpenBLAS.
For details of the issue, please see
https://docs.chainer.org/en/stable/tips.html#mnist-example-does-not-converge-in-cpu-mode-on-mac-os-x.

Also note that Chainer does not officially support Mac OS X.
Please use it at your own risk.

  ''')  # NOQA


In [2]:
x_data = np.array([5], dtype=np.float32)
x = Variable(x_data)  # trainableな変数となる

In [3]:
x, x.data

(variable([5.]), array([5.], dtype=float32))

In [4]:
y = x**2 -2 * x +1

In [5]:
y.data

array([16.], dtype=float32)

In [6]:
y.backward()  # backwordを行うと
x.grad  # それぞれの変数においての勾配が計算される．

array([8.], dtype=float32)

In [7]:
z = 2*x
y = x**2 - z +1
y.backward(retain_grad=True)
z.grad  # 中間の変数の勾配はメモリ効率のため，retain_grad=Trueとしないと解放される．

array([-1.], dtype=float32)

In [8]:
y.backward()  # そうしないと勾配を保持しない

In [9]:
z.grad is None

True

In [11]:
x.grad  # 最初の変数は勾配が常にある．

array([24.], dtype=float32)

In [17]:
x = Variable(np.array([[1, 2 ,3], [4, 5, 6]], dtype=np.float32))
y = x**2 -2*x +1
# 多次元配列を入力とするときは初期誤差を明示的に書かなければならない
y.grad = np.ones((2, 3), dtype=np.float32)
y.backward()
x.grad

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]], dtype=float32)

In [14]:
x = Variable(np.array([[1, 2 ,3], [4, 5, 6]], dtype=np.float32))
y = x**2 -2*x +1
# y.grad = np.ones((2, 3), dtype=np.float32)
y.backward()
x.grad is None

True